# Stop and Restart the stack
---
  - hosts: loadbalancer
    become: true
    gather_facts: false
    tasks:
      - name: ensure nginx stopped
        service: name=nginx  state=stopped

  - hosts: webserver
    become: true
    gather_facts: false
    tasks:
      - name: ensure apache2 stopped
        service: name=apache2  state=stopped

  # Restart mysql		
  - hosts: database
    become: true
    gather_facts: true
    tasks:
      - name: ensure mysql restarted
        service: name=mysql  state=restarted

  - hosts: webserver
    become: true
    gather_facts: false
    tasks:
      - name: ensure webserver started
        service: name=apache2  state=started

  - hosts: loadbalancer
    become: true
    gather_facts: false
    tasks:
      - name: ensure nginx started
        service: name=nginx  state=started


