---
# tasks file for nginx
- name: Install nginx
  apt: name=nginx state=present update_cache=yes

- name: Ensure nginx started
  service: name=nginx state=started enabled=yes

- name: Congigure nginx site
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0644
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: get active sites
  shell: ls -l /etc/nginx/sites-enabled 
  register: active 

- name: de-activate sites 
  file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
  with_items: active.stdout_lines
  when: item not in  sites
  notify: restart nginx 

- name: deactivate default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: activate demo nginx site
  file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
  with_dict: "{{sites}}"
  notify: restart nginx
